name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Just
      run: cargo install just
    - name: Lint
      run: just ci-lint
    - name: Build
      run: just ci-build
    - name: Run tests
      run: just ci-test
